server:
  port: 8761

# eureka.eureka.instance.hostname 设置当前实例的主机名称
# eureka.client.register-with-eureka 启动服务注册  当前设置是不将服务本身注册
# eureka.client.fetch-registery 检索服务
# eureka.server.enable-self-preservation 注册中心的保护机制 Eureka 会统计15分钟之内心跳失败的比例低于85%
#     将会触发保护机制，不剔除服务提供者，如果关闭服务注册中心将不可用的实例正确剔除
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
      waitTimeInMsWhenSyncEmpty: 0
      enableSelfPreservation: false